environment:
  matrix:
    - nodejs_version: "12"
    - nodejs_version: "10"
    - nodejs_version: "8"

platform:
  - x64

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - curl -L https://unpkg.com/@pnpm/self-installer | node
  - pnpm install

test_script:
  - pnpm test

matrix:
  fast_finish: true

build: off
